version: "3.8"
services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r5t!Q
      POSTGRES_DB: hotels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1q2w3e4r5t!Q@postgres:5432/hotels

volumes:
  postgres_data:
    name: postgres
