"""update booking

Revision ID: 11ac804d7701
Revises: 35a3fbebfd7a
Create Date: 2024-06-16 16:46:20.272720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ac804d7701'
down_revision: Union[str, None] = '35a3fbebfd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM booking')
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###
