"""add room images field

Revision ID: 430db2638ba8
Revises: 430db2638ba7
Create Date: 2024-06-16 18:12:51.629669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430db2638ba8'
down_revision: Union[str, None] = '4311f17b4062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO role (id, name, permissions) VALUES (1, 'user', null)")
    op.execute("INSERT INTO role (id, name, permissions) VALUES (2, 'admin', null)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE id = 1")
    op.execute("DELETE FROM role WHERE id = 2")
    # ### end Alembic commands ###
